### ISSUE TITLE
OpenCV: FFMPEG: format mp4 / MP4 (MPEG-4 Part 14) 

### ISSUE THREAD

**Issue by aleksmastermind2** [KQTENQK/MOT-DeepSort-CS#2]
Downloaded exe from the release, run the default command, put all files in one folder and this is error i get:

.\MOT_x64.exe -s source.mp4 -t target.mp4 -d yolo640v5.onnx -y 1 -m 2 -a osnet.onnx -v 0 -c .4

OpenCV: FFMPEG: format mp4 / MP4 (MPEG-4 Part 14)
fourcc tag 0x7634706d/'mp4v' codec_id 000C
fourcc tag 0x31637661/'avc1' codec_id 001B
fourcc tag 0x33637661/'avc3' codec_id 001B
fourcc tag 0x31766568/'hev1' codec_id 00AD
fourcc tag 0x31637668/'hvc1' codec_id 00AD
fourcc tag 0x7634706d/'mp4v' codec_id 0002
fourcc tag 0x7634706d/'mp4v' codec_id 0001
fourcc tag 0x7634706d/'mp4v' codec_id 0007
fourcc tag 0x7634706d/'mp4v' codec_id 003D
fourcc tag 0x7634706d/'mp4v' codec_id 0058
fourcc tag 0x312d6376/'vc-1' codec_id 0046
fourcc tag 0x63617264/'drac' codec_id 0074
fourcc tag 0x7634706d/'mp4v' codec_id 00A3
fourcc tag 0x39307076/'vp09' codec_id 00A7
fourcc tag 0x31307661/'av01' codec_id 801D
fourcc tag 0x6134706d/'mp4a' codec_id 15002
fourcc tag 0x63616c61/'alac' codec_id 15010
fourcc tag 0x6134706d/'mp4a' codec_id 1502D
fourcc tag 0x6134706d/'mp4a' codec_id 15001
fourcc tag 0x6134706d/'mp4a' codec_id 15000
fourcc tag 0x332d6361/'ac-3' codec_id 15003
fourcc tag 0x332d6365/'ec-3' codec_id 15028
fourcc tag 0x6134706d/'mp4a' codec_id 15004
fourcc tag 0x61706c6d/'mlpa' codec_id 1502C
fourcc tag 0x43614c66/'fLaC' codec_id 1500C
fourcc tag 0x7375704f/'Opus' codec_id 1503C
fourcc tag 0x6134706d/'mp4a' codec_id 15005
fourcc tag 0x6134706d/'mp4a' codec_id 15018
fourcc tag 0x6134706d/'mp4a' codec_id 15803
fourcc tag 0x7334706d/'mp4s' codec_id 17000
fourcc tag 0x67337874/'tx3g' codec_id 17005
fourcc tag 0x646d7067/'gpmd' codec_id 18807
fourcc tag 0x316d686d/'mhm1' codec_id 15817
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MOT.CORE.ReID.ReidScorer`1.Predict(Bitmap image, IPrediction[] detectedBounds)
   at MOT.CORE.Matchers.Deep.DeepMatcher.Run(Bitmap frame, Single targetConfidence, DetectionObjectType[] detectionObjectTypes)
   at MOT.Program.Main(String[] args)

**Comment by KQTENQK** [comment]
Could you provide me the source video file, please?
telegram: @kqtenqk
mail: xsx3xx@gmail.com

**Comment by aleksmastermind2** [comment]
Yep
Here > https://gofile.io/d/ib61yV

**Comment by aleksmastermind2** [comment]
Hello :)

Anything new about this issue?

**Comment by KQTENQK** [comment]
I’m sorry, do not have enough time to get into this, will fix as fast as i could

**Comment by KQTENQK** [comment]
Fixed
